# Login
POST http://localhost:3000/api/auth
Content-Type: application/json

{
  "email": "ricardo@email.com",
  "password": "123456"
}
###
# Login with Google
POST http://localhost:3000/api/auth/google
Content-Type: application/json

{
  "token": "ABC"
}