# Add image to user
PUT http://localhost:3000/api/uploads/users/657dd90fd38fcf31db02f567
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdjYjE1ZDE3MGJiMTY1NDNmOWNjYjMiLCJpYXQiOjE3MDM3ODk3MzcsImV4cCI6MTcwMzgzMjkzN30.vao3K8xYx9nNR7NKTnMnvIqiB5py7I3L041aHHwX-c4

###
# Get user image - api/uploads/{category}/{imageName}
GET http://localhost:3000/api/uploads/users/39271a69-b71c-44fc-b616-dcb25bcc1ed8.jpg
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdkZDkxNGQzOGZjZjMxZGIwMmY1NmEiLCJpYXQiOjE3MTEyOTM3ODcsImV4cCI6MTcxMTMzNjk4N30.XVyOOfj6X5fWXwMNKb-dVz4rG1b97Xqk3JLc5PpS6qY
###
# Get hospital image - api/uploads/{category}/{imageName}
GET http://localhost:3000/api/uploads/hospitals/8729ed72-e3e0-4947-9361-bffdfedba5d9.jpg
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdkZDkxNGQzOGZjZjMxZGIwMmY1NmEiLCJpYXQiOjE3MTEyOTM3ODcsImV4cCI6MTcxMTMzNjk4N30.XVyOOfj6X5fWXwMNKb-dVz4rG1b97Xqk3JLc5PpS6qY
###
# Get doctor image
GET http://localhost:3000/api/uploads/doctors/e3699437-efee-406f-aa06-a3f340b7f734.jpg
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdkZDkxNGQzOGZjZjMxZGIwMmY1NmEiLCJpYXQiOjE3MTEyOTM3ODcsImV4cCI6MTcxMTMzNjk4N30.XVyOOfj6X5fWXwMNKb-dVz4rG1b97Xqk3JLc5PpS6qY
