### Search all
GET http://localhost:3000/api/all/a
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdkZDkxNGQzOGZjZjMxZGIwMmY1NmEiLCJpYXQiOjE3MTEyMDU1NTksImV4cCI6MTcxMTI0ODc1OX0.q3P8Kc8K9FvZocDwhgsZzSrIJTkv-pGP4WecYVFGa88
### Search by collection
GET http://localhost:3000/api/all/collection/hospitals/cemesa
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdkZDkxNGQzOGZjZjMxZGIwMmY1NmEiLCJpYXQiOjE3MTEyMDU1NTksImV4cCI6MTcxMTI0ODc1OX0.q3P8Kc8K9FvZocDwhgsZzSrIJTkv-pGP4WecYVFGa88
