### Search all
GET http://localhost:3000/api/all/a
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdjYjE1ZDE3MGJiMTY1NDNmOWNjYjMiLCJpYXQiOjE3MDI4MzM3OTcsImV4cCI6MTcwMjg3Njk5N30.n6lnHI5N0UKfyYhTzOv83OMhFheBGUE6WJ5xJ7GeIlE
### Search by collection
GET http://localhost:3000/api/all/collection/users/e
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdjYjE1ZDE3MGJiMTY1NDNmOWNjYjMiLCJpYXQiOjE3MDI4MzM3OTcsImV4cCI6MTcwMjg3Njk5N30.n6lnHI5N0UKfyYhTzOv83OMhFheBGUE6WJ5xJ7GeIlE
