GET http://localhost:3000
### Get users
GET http://localhost:3000/api/users?from=0
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdjYjE1ZDE3MGJiMTY1NDNmOWNjYjMiLCJpYXQiOjE3MDkyNDQzNTMsImV4cCI6MTcwOTI4NzU1M30.08kOosTZW8Ugi40t8P9692MeS6GC3SgFVuMycj7GbCo


### Create user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "test17",
  "email": "test17@email.com",
  "password": "123456"
}
### Update user
PUT http://localhost:3000/api/users/657dd914d38fcf31db02f56a
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdjYjE1ZDE3MGJiMTY1NDNmOWNjYjMiLCJpYXQiOjE3MDkyNDQzNTMsImV4cCI6MTcwOTI4NzU1M30.08kOosTZW8Ugi40t8P9692MeS6GC3SgFVuMycj7GbCo
Content-Type: application/json

{
  "name": "test2",
  "email": "test2@email.com",
  "password": "123456",
  "role": "USER_ROLE",
  "google": false
}
### Delete user
DELETE http://localhost:3000/api/users/657ccc508f7f356d9f7a9342
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdjYjE1ZDE3MGJiMTY1NDNmOWNjYjMiLCJpYXQiOjE3MDI3NDAzMzIsImV4cCI6MTcwMjc4MzUzMn0.2ujVabRPSHBHZf49Cv4ALMdOj7Euv4-IC9IfiqLrCxc
