GET http://localhost:3000
### Get users
GET http://localhost:3000/api/users?from=0
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdjYjE1ZDE3MGJiMTY1NDNmOWNjYjMiLCJpYXQiOjE3MDMxMDE4NTcsImV4cCI6MTcwMzE0NTA1N30.zc23_mC0TWJupQAiq8F_bGE1gjpDp0D2ClsDBILDoKM

### Create user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "test15",
  "email": "test15@email.com",
  "password": "123456"
}
### Update user
PUT http://localhost:3000/api/users/657cb15d170bb16543f9ccb3
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdjYjE1ZDE3MGJiMTY1NDNmOWNjYjMiLCJpYXQiOjE3MDI2Nzg2MzEsImV4cCI6MTcwMjcyMTgzMX0.zztjLA4ml26G4jqsk4lkH5NJMP3g3ObDRjdy3yQ3lVQ
Content-Type: application/json

{
  "name": "Ricardo Corrales",
  "email": "ricardo@email.com",
  "password": "123456",
  "role": "USER_ROLE",
  "google": true
}
### Delete user
DELETE http://localhost:3000/api/users/657ccc508f7f356d9f7a9342
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTdjYjE1ZDE3MGJiMTY1NDNmOWNjYjMiLCJpYXQiOjE3MDI3NDAzMzIsImV4cCI6MTcwMjc4MzUzMn0.2ujVabRPSHBHZf49Cv4ALMdOj7Euv4-IC9IfiqLrCxc
