GET http://localhost:3000
### Get users
GET http://localhost:3000/api/users
### Create user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "daniel",
  "email": "daniel@email.com",
  "password": "123456"
}
### Update user
PUT http://localhost:3000/api/users/657cb15d170bb16543f9ccb3
Content-Type: application/json

{
  "name": "Ricardo Corrales",
  "email": "ricardo@email.com",
  "password": "123456",
  "google": true
}